### ISSUE TITLE
Battle not being record by system

### ISSUE THREAD

**Issue by thesunofme** [S1NJED/PixelTapBot#8]
The match went very normally, but I don't see it being recorded, my account still shows a total of 5 matches no matter how many matches the script plays. After finishing the match, I still receive a notification that I won or lost, the amount of money deducted or added.

**Comment by S1NJED** [comment]
It does count it's just that they changed things so now the balance is updated every 3-4 fights for some reasons.

**Comment by ilcham0202** [comment]
please check this one
